### ISSUE TITLE
Verificar licencia Windows

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/becas2018#1]
Verificar que las PC del laboratorio de Redes estén con Windows Activado. En caso de no tenerlo activado, gestionar la licencia con Gesin.

**Comment by sergioviera** [comment]
prueba

**Comment by LSIUTN** [comment]
Testing

2018-05-14 19:36 GMT-03:00 Sergio Viera <notifications@github.com>:

**Comment by nachocagnoni** [comment]
Se finalizó la activación de las PC's.
