### ISSUE TITLE
verificar conección aula 4to

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/becas2018#21]
No está funcionando la conección a Internet (y la red LSI) en el aula de 4to de Sistemas. [Ver TDC](http://lsi.no-ip.org/tdc/)

**Comment by lsi-frd-utn** [comment]
El problema está en que el conector al router de 4to está suelta la ficha
RJ45.
Hay un issue para cambiar el swich de 4to y revisar la conexion. quizas hay
que cerrar este issue por duplicado.


2018-05-29 13:34 GMT-03:00 Sergio Viera <notifications@github.com>:

**Comment by sergioviera** [comment]
No está bien, dejala, porque la otra verifica las PC recién conectadas.
Saqué un router de 8 bocas y dejé solo el router WIFI. Reemplacé el toma por una ficha.
