### ISSUE TITLE
Virtualizar Server - IngSoft.

### ISSUE THREAD

**Issue by nachocagnoni** [UTN-FRD/becas2018#23]
Se necesita crear un servidor virtual para Ingeniería de Software: SO: Linux Ubuntu Server

**Comment by nachocagnoni** [comment]
Se creo el servidor Virtual en xenserver con nombre IngSofVM - hostname ingsoft : xxx

**Comment by sergioviera** [comment]
Hay que pasarle el IP y las credenciales a los alumnos involucrados.

2018-06-07 18:54 GMT-03:00 Ignacio <notifications@github.com>:

**Comment by nachocagnoni** [comment]
Se dio de alta el servidor virtual. 

Usuario: ingsoft
IP: xxx.xxx.xxx.73
Hostname: IngSoft
