### ISSUE TITLE
SRAT - Migración.

### ISSUE THREAD

**Issue by nachocagnoni** [UTN-FRD/becas2018#27]
Migracion de cada una de las BD a una sola BD en el Servidor.

**Comment by nachocagnoni** [comment]
Hola Jorge, como estas ?
Armé este "Issue" para ver si me podes comentar hasta donde se llegó o como te parece que hagamos para que podamos avanzar con unificaicon de la BD.

**Comment by jacricelli** [comment]
Todo está en SvrLsi y no estoy al tanto que haya otras bases de datos fuera de ese servidor.

**Comment by lsi-frd-utn** [comment]
Gracias Jorge, Se migraron las 4 bases a una 1 sola  en ese servidor o bien
hay que realizar dicha migracion/unificacion de bases.?

**Comment by jacricelli** [comment]
Por las dudas, cuáles son esas 4 bases de datos?

**Comment by nachocagnoni** [comment]
Serian la de Sistema, mecanica, electrica y quimica, todas migradas en una sola, asi apuntamos con la aplicacion a una sola base.

**Comment by nachocagnoni** [comment]
Si eso no está avisame asi procedemos a asignar a uno de los chicos para avanzar con el analisis de unificar las 4 en una sola.

**Comment by jacricelli** [comment]
Confirmame si cablearon y cada máquina que tiene la aplicación está
conectada a la red del laboratorio.

**Comment by nachocagnoni** [comment]
Se cierra por upgrade SRAT 2019
