### ISSUE TITLE
Instalar Matlab

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/becas2018#3]
Instalar Matlab en:

- [x] Laboratorio L44 
- [x] Laboratorio L45
- [x] Notebooks

**Comment by sergioviera** [comment]
ver check list enviado por email

**Comment by lsi-frd-utn** [comment]
Se instalo el software en en la mayoría de las PC. (Faltan en 2). Además Deben y realizar la activación dado que no funciona.

**Comment by nachocagnoni** [comment]
Se instalo el software en todas las PC. Continuar con siguiente check point.

**Comment by nachocagnoni** [comment]
Quedan check point para completar esta tarea, recordar que queda pendiente instalar el software en :
  Laboratorio L44  y las Notebooks.

  Finalizado en Laboratorio L45

**Comment by nachocagnoni** [comment]
Finalizado en Laboratorio L44
Finalizado en Laboratorio L45

Queda pendiente instalar el software en Notebooks.

**Comment by ValentinMorali** [comment]
Notebooks 1 - 4 - 5 - 6 listas

**Comment by ValentinMorali** [comment]
Notebooks 1 - 4 - 5 - 6 - 11 - 12 listas

**Comment by ValentinMorali** [comment]
Notebooks LISTAS, solo falta la numero 2.
