### ISSUE TITLE
Actualización Aula 4° Sistemas.

### ISSUE THREAD

**Issue by nachocagnoni** [UTN-FRD/becas2018#6]
- [x] Instalar Placa de RED WiFi a 3 PC (PC5, PC6 PC1)
- [x] Instalar MatLab
- [x] Trasladar las 3 PC a 4° Sistemas.
- [x] Verificar conexión red Intranet/Internet

**Comment by nachocagnoni** [comment]
@ValentinMorali perdon, esta tarea empezamos.

**Comment by ValentinMorali** [comment]
Matlab en PC 5 y 6 listo

**Comment by nachocagnoni** [comment]
Finalizado.
