### ISSUE TITLE
Seleccionar CMS

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/becas2018#7]
- [x] Seleccionar un CMS (ver Wordpress, Joomla, etc)

**Comment by sergioviera** [comment]
@jacricelli tenés alguna preferencia de CMS? Wordpress/Joomla etc?

**Comment by jacricelli** [comment]
Tengo experiencia con WordPress/Drupal y algún otro.

Mañana levanto un WordPress para probar.

Joomla 👎

**Comment by sergioviera** [comment]
Jaja.

Usamos WordPress entonces! Lo podrá instalar un becado?

**Comment by jacricelli** [comment]
Sí, no es complicado.

Enviado desde mi Moto G5 Plus
